name: WoI.AdvancedCompass
main: ca.qc.icerealm.bukkit.plugins.advancedcompass.AdvancedCompass
version: 0.1.0
description: Advanced compass utilities
author: Draskus
softdepend: [Vault]
commands:
  C:
    description: Command to use set compass location