name: WoI.Quests
main: ca.qc.icerealm.bukkit.plugins.quests.QuestPlugin
version: 0.3.0
description: World Of IceRealm Quests
author: Allov
softdepend: [Vault]
commands:
  Q:
    description: Command to use to start an IceRealm quest.