name: WoI.Quests
main: ca.qc.icerealm.bukkit.plugins.quests.Quests
version: 0.1.0
description: World Of IceRealm Quests
author: Allov
softdepend: [Vault]
commands:
  Q:
    description: Command to use to start an IceRealm quest.