name: WoI.Scenarios
main: ca.qc.icerealm.bukkit.plugins.scenarios.core.ScenarioPlugin
version: 1.1.6
description: World Of IceRealm Scenarios!
author: punihser_malade

commands:

  fr:
    description: frontier command control
  am:
    description: ambush command control
  ev:
    description: event service control
