name: WoI.Scenarios
main: ca.qc.icerealm.bukkit.plugins.scenarios.core.ScenarioPlugin
version: 0.1.0
description: World Of IceRealm Scenarios!
author: punihser_malade

commands:
  cs:
    description: Castle Siege infestation configuration
  pl:
    description: Ruins plateform infestation configuration
  sc:
    description: general scenario commands
 
