name: WoI
main: ca.qc.icerealm.bukkit.plugins.scenarios.ScenarioPlugin
version: 0.0.0
description: World Of Icerealm Scenarios!
author: punihser_malade

commands:
  sc:
    description: Enable the scenario mode
